CREATE TYPE "AppModule" AS ENUM ('DASHBOARD', 'CLIENTES', 'RH', 'COMERCIAL', 'OPERACOES', 'FINANCAS');

CREATE TYPE "CompanyPlanTier" AS ENUM ('BASICO', 'PRO', 'EMPRESARIAL');

CREATE TYPE "UserRole" AS ENUM ('ADMIN', 'EMPLOYEE');

CREATE TYPE "UserStatus" AS ENUM ('ACTIVE', 'BLOCKED');
