ALTER TABLE "Product" ALTER COLUMN "stockValue" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "averageCost" SET DATA TYPE DECIMAL(18,6);

ALTER TABLE "StockMovement" ALTER COLUMN "unitCost" SET DATA TYPE DECIMAL(18,6),
ALTER COLUMN "valueDelta" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "valueBefore" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "valueAfter" SET DATA TYPE DECIMAL(20,6),
ALTER COLUMN "averageCostBefore" SET DATA TYPE DECIMAL(18,6),
ALTER COLUMN "averageCostAfter" SET DATA TYPE DECIMAL(18,6);
